apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

djangotest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from graphene_django.views import GraphQLView
from django.conf import settings

urlpatterns = [
    path('blog/', include('apps.blog.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('graphql/', GraphQLView.as_view(graphiql=True)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/blog/models.py
from .submodels.article import *
from .submodels.comment import *

apps/user/models.py
from django.db import models

# Create your models here.

apps/blog/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from .models import Article
from django.urls import reverse
import datetime


def index(request):
    latest_article_list = Article.objects.order_by('-date_create')[:5]
    return render(request, 'blog/list.html', {'data': latest_article_list})


def detail(request, article_id):
    try:
        detail_page = Article.objects.get(id=article_id)
    except:
        raise Http404('Страница не найдена')

    comment_list = detail_page.comment_set.order_by('-id')[:10]
    return render(request, 'blog/detail.html', {'data': detail_page, 'comments': comment_list})


def leave_comment(request, article_id):
    try:
        detail_page = Article.objects.get(id=article_id)
    except:
        raise Http404('Страница не найдена')

    detail_page.comment_set.create(author_name=request.POST['name'], text=request.POST['text'], date_create=datetime.datetime.now())
    return HttpResponseRedirect(reverse('blog:detail', args=(detail_page.id,)))

apps/user/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
</head>
<body>
    {% block content %}Контент{% endblock %}
</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}Статья - {{ data.title }}{% endblock %}

{% block content %}
    {% if data %}

        <h1>{{ data.title }}</h1>
        <p>{{ data.text }}</p>
        <em>{{ data.date_create }}</em>

        <hr>
            {% if comments %}
                {% for com in comments %}
                    <p>
                        <strong>{{ com.author_name }}</strong>
                        от <em>{{ com.date_create }}</em>
                        <p>{{ com.text }}</p>
                    </p>
                {% endfor %}
            {% else %}
                Ничего нет
            {% endif %}
        <hr>

        <form action="{% url 'blog:leave_comment' data.id %}" method="post">
            {% csrf_token %}
            <input type="text" required placeholder="Ваше имя" name="name"></br>
            <textarea name="text" required cols="50" rows="10" placeholder="Текст комментария"></textarea></br>
            <button type="submit">Оставить комметарий</button>
        </form>

    {% else %}
        Ничего нет
    {% endif %}

{% endblock %}

templates/blog/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}
    {% if data %}

        {% for a in data %}
            <a href="{% url 'blog:detail' a.id %}">{{ a.title }}</a>
        {% endfor %}

    {% else %}
        Ничего нет
    {% endif %}

{% endblock %}